class TimeAxis:
    @staticmethod
    def from_values(values: list[float]) -> TimeAxis: ...
    @staticmethod
    def from_bounds(values: list[float]) -> TimeAxis: ...
    def values(self): ...
    def bounds(self): ...

class Timeseries: ...
